apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-env-secrets
  namespace: kube-keycloak
spec:
  encryptedData:
    KC_DB_PASSWORD: AgBNw5GVgX3RxOFw0HyJ2sRKqwXlrpzkshhJ1Ct3xOEfFZk/DqHqG28jZdz5XShko3wZ/Fvc/mezRPXGQpP5qG3oSaIvzvKO7XJf/GAQby4vMsG0vLDHJKKpv0OmYEwF5YKVyKQ3XzGR9lOtj6zkGUU9FT25Gj4eqt5LhoZ8UPJN4zpajseZN7xrBJWWNJ/Veigt+FJfjMJE/pmJmN9zA4ZdkLdvHg+eP3rIaMFheSVqorWC2rbHSr1HH8xRa6iGrOeyhCugBSlM7uiDBrZrcDStiEBWyn10NMdEy4x0rNh/95dyJr5R8lVo2tQKq1Etu9EeeDJdsaN4b7gHJROBCHW+qgP+XjpTJ37/vaYb9rztyRbTAx9v3Kgwc/44Y5cTdAlfaQJkuzAiB3LiS+oIwc/bbTAn/gqRoRdnpIhw4+5Ry5ZlRjm5iOLhG5qdVelVHLBCVzGD3Sm/AVjpSVY/7DxFMTfoj62M21DY/H0jskIhCRDxVGrhrvL/7rRV3RYqRomy1TP64557A7/H9UHeRmVy+PnugxuRdttIwX2YrKrMdc4HmqVhL62JNipAngDZtbNAxW1h1oqO0k62TaLrWlTP8xGFmKoDBxRQTiFYh7pkiodu0Be3KM99hnIVXM8v6F2bycPwzTHdEBqTLqwDioSNp/VKqptyfS9G25wLqTa3LhZfl3vkyXwg2VdLkfv/ieK9BQGMttjLSA==
    KEYCLOAK_ADMIN_PASSWORD: AgBQaMptIqamiDgwWQnkPrgcyT1CaNYRrMfPPXSr4aIHQ7IsnNTBab+0eAi0Q92fuBaeYzz9ao4fDG5IzNyUEyfZCWbsqScs8R/wtSpY9wZdWSaHETYPVWSMSzWd6/uCTdk9vTkhLEdUZbxJGDenecOdvJM2x5/ARkZDal/cjbQaiueTdg7nahaaAmgzgPmMM67Up4wR34cT5zvpmo6fuYVose8zs1tEQ/z/RAXV7HlgWESe84ZYOITBblHraDqsoZ5gtzapghAsU1Wr6y+6mHL4wwf3sxbE9LNWAl/3TBFiGI1v0Z3Ck9jMB5adjnJKsXAgFEQRxRnfgx+uBH6/Y69/s8FKf9NtSGTQeZ+MTNjXB4yttVfM6osvqjH5hH6dqkoQxi2CHV+XYajtv9v8Gip3MgrSSATgLy4qQJASmEA4xSKeMGG9hql43MAX5VCxO0797x53+iVgwuI773Yo7NJFZuU0Ez8gWwl+ggV8n7TZkGj/rkDzCkyXLwQul54YaDy753aquAZBVrPfuYfipjVu67dJSxYXkhJhdoIr/j5BNbTi0IZc3Lr2djj1L5lQXMRgiLFURm3cTF404NUaefT+nAz9jftg2sSP48FPplsDt9IyCSA5Ru5kClWRqhBluJTivbHujtKiFMFP1WV+ihPEgBqH/sc6xGli17epO06/tzdetlA+8liITD39qK8VaxD2Y72Eeg==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-env-secrets
      namespace: kube-keycloak
    type: Opaque

