apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-argocd

resources:
- resources/argo-core-appset.yaml
- resources/argo-tenants-appset.yaml
- resources/tenantsproject.yaml
- resources/argocd-rbac-policy.yaml
- secrets/github-sealed-secret.yaml
