apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:21.0.1
        args: ["start --hostname=home.keycloak --https-certificate-file=/tlskeys/tls.crt --https-certificate-key-file=/tlskeys/tls.key"]
        env:
        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: keycloak-env-secrets
              key: KEYCLOAK_ADMIN_PASSWORD
        - name:	KC_DB
          value: "mariadb"
        - name:	KC_DB_USERNAME
          value: "keycloak"
        - name:	KC_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: keycloak-env-secrets
              key: KC_DB_PASSWORD
        - name: KC_DB_URL
          value: "jdbc:mariadb://127.0.0.1/keycloak"
        - name: KC_PROXY
          value: "edge"
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
        volumeMounts:
          - mountPath: /tlskeys
            name: keycloak-tls
      - name: keycloakmariadb
        image: mariadb
        ports:
        - name: keycloakdb
          containerPort: 3306 
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "0" 
        - name: MARIADB_ROOT_PASSWORD
          value: secret
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: db-data
      # Volumes attached to the pod
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: keycloak-mariadb-pvc
        - name: keycloak-tls
          secret:
            secretName: keycloak-tls
            optional: true
       

