apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-keycloak

resources:
- resources/keycloak-service.yaml
- resources/keycloak-deployment.yaml
- resources/keycloak-namespace.yaml
- resources/keycloak-mariadb-pvc.yaml
- secrets/keycloak-env-secrets.yaml

