apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- config/smb-csi-storageclass.yaml
- config/rbac-csi-smb.yaml
- csi-smb-driver/csi-smb-controller.yaml
- csi-smb-driver/csi-smb-driver.yaml
- csi-smb-driver/csi-smb-node-windows.yaml
- csi-smb-driver/csi-smb-node.yaml
